#!/bin/bash

CMD=$1

export JENKINS_HOME=/opt/jenkins

JAVA_HOME=/opt/jre1.6.0_27
JENKINS_VER=stable
PREFIX="/jenkins"
HOST="dev1.vayana.in"
URL="https://$HOST$PREFIX"

case $CMD in
    start)
        echo -n "Starting Jenkins... "

        $JAVA_HOME/bin/java \
            -jar $JENKINS_HOME/$JENKINS_VER.war \
            --prefix=$PREFIX \
            --logfile=/var/log/jenkins.log \
            --httpPort=-1 \
            --ajp13ListenAddress=127.0.0.1 \
            </dev/null >>/var/log/jenkins.log 2>&1 &

        JENKINS_PID=$!
        RETVAL=$?
        echo "started at $JENKINS_PID"
        ;;
    stop)
        echo -n "Stopping Jenins... "

        HTTP_CODE=$(curl -skfw "%{http_code}" $URL/exit)

        [ $HTTP_CODE -eq 503 ] && RETVAL=0 || RETVAL=$?
        [ $RETVAL -eq 0 ] && echo "done" || echo "failed"
        ;;
    reload)
        echo -n "Reloading Jenins... "

        curl -skf $URL/reload

        RETVAL=$?
        echo "done"
        ;;
    restart)
        $0 stop 
        $0 start
        RETVAL=$?
        ;;
    status)
        echo -n "Verifying Jenkins... "

        curl -skf $URL

        RETVAL=$?
        [ $RETVAL -eq 0 ] && echo "up" || echo "down"
        ;;
    *)
        echo "Usage: $0 {start|stop|reload|restart|status}"
        RETVAL=1
esac

exit $RETVAL
